# render.yaml
services:
  - type: web
    name: todo-api
    env: docker
    buildCommand: docker build -t todo-api .
    startCommand: docker run -p $PORT:80 todo-api
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: todo_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: todo_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: todo_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: todo_db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: todo_db
          property: password

databases:
  - name: todo_db
    plan: free
